### ISSUE TITLE
yarn dev fails on Windows 10 64-bit

### ISSUE THREAD

**Issue by cmarabate** [CodePilotai/codepilot#10]
![image](https://user-images.githubusercontent.com/12236062/78807691-6a126d00-7992-11ea-89e8-33213ff49b20.png)

**Comment by cameronadams777** [comment]
@cmarabate This is due to an incompatibility issue with your version of node and the version of `node-sass` that is installed in the project. I have an open PR that will update the version of `node-sass` so that it supports the current LTS version of Node.
