### ISSUE TITLE
Compromised dependency flatmap-stream

### ISSUE THREAD

**Issue by sparebytes** [CodePilotai/codepilot#3]
The `yarn.lock` file contains the compromised `flatmap-stream@0.1.1` package which attempts to steal bitcoin wallets from the user's system. I'm concerned the `5.0.0` release has it embedded.

https://github.com/dominictarr/event-stream/issues/116

**Comment by petebytes** [comment]
@sparebytes Thanks for reporting this!
Looks like it impacts codepilot in dev as it is a nested dependency of npm-run-all@4.1.3 -> ps-tree@^1.1.0 -> event-stream@3.3.6 -> flatmap-stream

Actions:
- Updated master npm-run-all from 4.1.3 to 4.1.5
- Adding notice to embedded landing page.
- Deleted binaries from 5.0.0

The above changes replaces ps-tree package with pidtree which removes the flatmap-stream dependency.

**Comment by CameronAdams777** [comment]
@petebytes Because you addressed this, can the issue be closed now?
