### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [CodePilotai/codepilot#4]
https://github.com/CodePilotai/codepilot/blob/e99b581326ddd913f7ea968344d80e9518b048d6/package.json#L160

Where can the [AppImage](https://appimage.org/) be downloaded?

**Comment by petebytes** [comment]
@probonopd the "AppImage" is the target package type, see https://www.electron.build/configuration/linux

What are you trying to do? Is the build not working?

**Comment by petebytes** [comment]
When we open sourced the project we decided to no longer provide binaries.
You can build your own. Checkout the build steps in the readme.
If you have issues or additional questions please let me know.

**Comment by probonopd** [comment]
> When we open sourced the project we decided to no longer provide binaries.

While I respect your opinion, it'd still be more convenient to download binaries. I could then also include the application on [AppImageHub](https://appimage.github.io).

**Comment by petebytes** [comment]
Yes it would be more convenient :)
A major reason for the decision was due to several API keys in services.config.js that should be changed prior to build.

**Comment by hiringManager** [comment]
Any information on where I can get the appimage? It is listed on numerous appimage listings, but no location to download it.
