### ISSUE TITLE
How to download ?

### ISSUE THREAD

**Issue by AnatoleLucet** [CodePilotai/codepilot#6]
Hi so i can't find any download for a setup or something like that.
Do i have to download the source code and start the app with electron or i there any installation setup ?

**Comment by petebytes** [comment]
We do not have a binary download available.  Partly due to the need for multiple API keys that you should configure.
The readme shows how to build the binary, but perhaps that part is confusing.
- Download the repo
- Run yarn install
- Add your keys to services.config.js
- Then run yarn build:production

**Comment by AnatoleLucet** [comment]
@petebytes Ok i'll do this, thanks you

**Comment by mbarqawi** [comment]
thank you for the great work I used it before but I can't find it now
I simply want an EXE to run, what are these keys

**Comment by petebytes** [comment]
We do not have a binary(exe) download available.
The keys are used to access the services codepilot uses such as Github.

To create the exe:
    Download the repo
    Run yarn install
    Add your keys to services.config.js
    Then run yarn build:production

**Comment by AnatoleLucet** [comment]
@petebytes I was thinking; is there any reason to not do a fully compiled binary executable file (or maybe an installer) and then when the app start ask to the user to enter hes keys in some inputs, a little bit like a login ?

**Comment by petebytes** [comment]
@AnatoleLucet That would be great. My preference would be to have the binaries read from external config and provide UI in the app to update. (instead of installer).

**Comment by AnatoleLucet** [comment]
@petebytes Yes sorry I misspoke, this could not be really practical if the user have to enter some keys in the installer. But the UI in the app for doing this is a great idea, I hope this will pops out 😉
