### ISSUE TITLE
Is there a way to open this with a .exe file?

### ISSUE THREAD

**Issue by cmarabate** [CodePilotai/codepilot#9]
It seems odd to me that an app would require you to open the directory in command prompt and start using a command.

I know how to do all that but I don't see myself doing that every time I want to open the app. If it was able to open from an .exe file like every other app I've ever installed, I could then create a AutoHotkey Script to toggle it open and closed with a single hotkey. Then I would use it for sure!

**Comment by petebytes** [comment]
@cmarabate if you generate a build you can then install the application and start like normal.
Where are you seeing the directions to start?

**Comment by cmarabate** [comment]
Is there a reason that this is not already done for me? I want to just be able to open a file that will install the software on my computer for me or if this is a portable app then I would want all the files required to run it from the .exe file within it. I don't feel like I should have to generate a build myself but I might be misunderstanding how this software works.

Not sure I understand your question but I see all your directions on https://github.com/CodePilotai/codepilot if that is what you are referring to. But it is all very overwhelming. I am a web developer so I have some knowledge about that kind of stuff but I have never developed an app before.

Thanks!

**Comment by petebytes** [comment]
Yeah - the API keys are embedded in the app executable.  So we have provide directions on how to create an app using you own keys.
The process is not the easiest :(

**Comment by cmarabate** [comment]
Ahhh, I knew there had to be a reason! Thank you for explaining that to me.

I may try it out if I get the time because it does seem really cool. I'm just hesitant to put a lot of time into something I don't even know that I will actually use or even be able to get working properly.

Thanks again!
